# Generated by Django 4.0.6 on 2022-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(default=1)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('local', models.CharField(choices=[('FRIG', 'Frigorifico'), ('DESP', 'Despensa')], default='FRIG', max_length=5)),
                ('categoria', models.CharField(choices=[('LEG', 'Legume'), ('LAC', 'Lacticinio')], default='LEG', max_length=5)),
            ],
        ),
    ]
