# Generated by Django 4.0.6 on 2022-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, default=' - ', max_length=100),
        ),
    ]
